linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/hackmajoris/analyze-me

issues:
  exclude-use-default: false
